#####################
## grunt-purgecss ##
#####################
###
[OVERVIEW] Remove unused CSS:
https://www.purgecss.com/

[INFO] Grunt wrapper:
https://purgecss.com/plugins/grunt.html


[NOTE] dropcss possibly is better than alternatives:
https://github.com/leeoniya/dropcss#output

but it haven’t integrations for Grunt, PostCSS or similar tools:
https://github.com/leeoniya/dropcss/issues/3#issuecomment-586776876
https://github.com/leeoniya/dropcss/issues/45#issuecomment-615054364


[INFO] Comparison with PurifyCSS and UnCSS:
https://www.purgecss.com/comparison

[WARNING] I couldn’t find, how I can ignore scripts in UnCSS:
https://github.com/uncss/uncss/issues/321
So that I select PurgeCSS, not UnCSS.


[INFO] PurifyCSS not maintained since March 2018:
https://github.com/purifycss/purifycss/issues/213


[INFO] UnusedCSS isn’t open source:
https://unused-css.com/


[INFO] Needs separate task for each theme.
[FIXME] PostCSS PurgeCSS plugin exists, and it’s more modern solution than grunt-purgecss.
But I don’t know, how I can do separate tasks for it:
https://github.com/FullHuman/purgecss/tree/master/packages/postcss-purgecss

[INFO] PurgeCSS supports elements, that include via simply methods.
[EXAMPLE] “<div class="SashaClass"></div>” in HTML;
“.SashaClass { color: black }” in CSS;
If elements generated by JavaScript, PurifyCSS doesn’t work,
use safelisting
###
module.exports =

	options:

		###
		[NOTUSED] Because Wildfire no longer maintained

		[INFO] Safelisting patterns:
		https://purgecss.com/safelisting.html#patterns
		safelist:

			[INFO] Wildfire selectors.
			[LINK] “..\themes\sashapelican\static\stylus\sections\wildfire.styl”

			[NOTE] Use “greedy”;
			“standard” and “deep” doesn’t work in my case

			greedy: [/wf-theme-dark$/
					/animate-flicker$/
					/ivu-modal-body$/]
		###

		sourceMap: true


	bulmatarget:
		options:
			###
			[INFO] Any category can be used here.
			I use the same syntax for all articles and pages.
			###
			content: [
				"<%= templates.yamlconfig.OUTPUT_PATH %>/Sublime-Text/*.html"
				]
		files:
			"<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/third-party/Bulma/bulma-modules.css": \
			["<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/third-party/Bulma/bulma-modules.css"]

	foresttarget:
		options:
			content: [
				"<%= templates.yamlconfig.OUTPUT_PATH %>/authors.html"
				"<%= templates.yamlconfig.OUTPUT_PATH %>/categories.html"
				"<%= templates.yamlconfig.OUTPUT_PATH %>/author/*.html"
				"<%= templates.yamlconfig.OUTPUT_PATH %>/category/*.html"
				"<%= templates.yamlconfig.OUTPUT_PATH %>/tag/*.html"
				]
		files:
			"<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/forest.css": \
			["<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/forest.css"]

	gingerinastarget:
		options:
			content: [
				"<%= templates.yamlconfig.OUTPUT_PATH %>/Nelias-Rooms/*.html"
				"<%= templates.yamlconfig.OUTPUT_PATH %>/Gingerinas/*.html"
				]
		files:
			"<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/gingerinas.css": \
			["<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/gingerinas.css"]

	giologicabluetarget:
		options:
			content: ["<%= templates.yamlconfig.OUTPUT_PATH %>/Giologica/Valerywork-Kiravel.html"]
		files:
			"<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/giologica-blue.css": \
			["<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/giologica-blue.css"]

	giologicatarget:
		options:
			content: [
				"<%= templates.yamlconfig.OUTPUT_PATH %>/Books-Reviews/*.html"
				"<%= templates.yamlconfig.OUTPUT_PATH %>/Gingerinas/Библиотека-для-джинджерин.html"
				"<%= templates.yamlconfig.OUTPUT_PATH %>/Gingerinas/Таблицы-поиска-книг-для-джинджерин.html"
				"<%= templates.yamlconfig.OUTPUT_PATH %>/Giologica/*.html"
				"<%= templates.yamlconfig.OUTPUT_PATH %>/G-Rights/*.html"
			]
		files:
			"<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/giologica.css": \
			["<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/giologica.css"]

	indextarget:
		options:
			content: ["<%= templates.yamlconfig.OUTPUT_PATH %>/index.html"]
		files:
			"<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes-specific/kristinita.css": \
			["<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes-specific/kristinita.css"]

	itarticlestarget:
		options:
			content: [
				"<%= templates.yamlconfig.OUTPUT_PATH %>/Nelias-Rooms/*.html"
				"<%= templates.yamlconfig.OUTPUT_PATH %>/IT-articles/*.html"
				]
		files:
			"<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/it-articles.css": \
			["<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/it-articles.css"]

	programstarget:
		options:
			content: [
						"<%= templates.yamlconfig.OUTPUT_PATH %>/Nelias-Rooms/*.html"
						"<%= templates.yamlconfig.OUTPUT_PATH %>/Sublime-Text/*.html"
						]
		files:
			"<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/programs.css": \
			["<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/programs.css"]

	sashablacktarget:
		options:
			content: [
				"<%= templates.yamlconfig.OUTPUT_PATH %>/Sasha-Black/*.html"
				"<%= templates.yamlconfig.OUTPUT_PATH %>/Pages/*.html"
			]
		files:
			"<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/sasha-black-description.css": \
			["<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/sasha-black-description.css"]

	smertsvobodetarget:
		options:
			content: ["<%= templates.yamlconfig.OUTPUT_PATH %>/Smert-svobode/*.html"]
		files:
			"<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/smert-svobode.css": \
			["<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes/smert-svobode.css"]

	# [NOTE] “404target” invalid for CoffeeScript
	target404:
		options:
			content: ["<%= templates.yamlconfig.OUTPUT_PATH %>/404.html"]
		files:
			"<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes-specific/404.css": \
			["<%= templates.yamlconfig.OUTPUT_PATH %>/<%= templates.yamlconfig.THEME_STATIC_DIR %>\
			/css/nelican-themes-specific/404.css"]
