#####################
## grunt-purifycss ##
#####################
# Remove unused CSS for Kristinita.ru design
# https://www.npmjs.com/package/purify-css
# https://www.npmjs.com/package/grunt-purifycss
# [NOTE] Needs separate task for each style. Because different styles in Kristinita.ru
# [BUG] Doesn't work with grunt-newer:
# https://github.com/purifycss/grunt-purifycss/issues/30
module.exports =
	options:
		# [WARNING] PurifyCSS support elements, that include simply methods.
		# Example: <div class="SashaClass"></div> in HTML;
		# .SashaClass { color: black } in CSS;
		# If elements generated by JavaScript, PurifyCSS doesn't work:
		# https://github.com/purifycss/purifycss/issues/194
		whitelist: [
					'.tooltipster-punk-purple .tooltipster-box'
					'.tooltipster-punk-aquamarine .tooltipster-box'
					]
	sublimetexttarget:
		src: [
				'<%= templates.paths.output_path %>/Sublime-Text/*.html'
				'<%= templates.paths.output_path %>/Programs/*.html'
				]
		css: ['<%= templates.paths.output_path %>/theme/css/sections/sublime-text.css']
		dest: '<%= templates.paths.output_path %>/theme/css/sections/sublime-text.css'
	gingerinastarget:
		src: ['<%= templates.paths.output_path %>/Gingerinas/*.html']
		css: ['<%= templates.paths.output_path %>/theme/css/sections/gingerinas.css']
		dest: '<%= templates.paths.output_path %>/theme/css/sections/gingerinas.css'
	itarticlestarget:
		src: ['<%= templates.paths.output_path %>/IT-articles/*.html']
		css: ['<%= templates.paths.output_path %>/theme/css/sections/it-articles.css']
		dest: '<%= templates.paths.output_path %>/theme/css/sections/it-articles.css'
	giologicabluetarget:
		src: ['<%= templates.paths.output_path %>/Giologica/Valerywork-Kiravel.html']
		css: ['<%= templates.paths.output_path %>/theme/css/sections/giologica-blue.css']
		dest: '<%= templates.paths.output_path %>/theme/css/sections/giologica-blue.css'
	giologicatarget:
		src: ['<%= templates.paths.output_path %>/Giologica/*.html']
		css: ['<%= templates.paths.output_path %>/theme/css/sections/giologica.css']
		dest: '<%= templates.paths.output_path %>/theme/css/sections/giologica.css'
	sashablacktarget:
		# Pages and Sasha Black
		src: [
				'<%= templates.paths.output_path %>/Sasha-Black/*.html'
				'<%= templates.paths.output_path %>/Pages/*.html'
				]
		css: ['<%= templates.paths.output_path %>/theme/css/sections/sasha-black-description.css']
		dest: '<%= templates.paths.output_path %>/theme/css/sections/sasha-black-description.css'
	smertsvobodetarget:
		src: ['<%= templates.paths.output_path %>/Smert-svobode/*.html']
		css: ['<%= templates.paths.output_path %>/theme/css/sections/smert-svobode.css']
		dest: '<%= templates.paths.output_path %>/theme/css/sections/smert-svobode.css'
